; --------------------------------
; Mnozenie dwoch liczb 8-bitowych
; czynniki: B,C. Iloczyn: HL
; --------------------------------
mul8::		push	bc
		push	de

		ld	hl,0
		ld	a,c
		ld	d,0
		ld	e,b
		ld	b,8			; licznik bitow		
	loop:	add	hl,hl
		rla
		jr	nc,skip
		add	hl,de
	skip:	djnz	loop

		pop	de
		pop	bc
		ret		
	
; -----------------------------------
; Mnozenie takich liczb aby iloczyn 
; byl 8-bitowy. 
; czynniki: B,C   iloczyn: A
; -----------------------------------
; mulproduct8::
;		push	bc
;		ld	a,0
;	nxtadd:	add a,c
;		djnz nxtadd
;		pop	bc
;		ret
; Szybsza dla duzych mnoznikow ( > 8 )
; mulproduct8::
;		push	bc
;
;		ld	a,0
;	loop1:	bit	0,b
;		jr	z,skip2	
;		add	a,c
;	skip2:	sla	c
;		srl	b
;		jr	nz,loop1
;		pop	bc
;		ret


; --------------------------------------
; Zamiana 2-cyfrowej liczby dziesietnej 
; w formacie ASCII na liczbe 8-bit
; input: (HL)	output: A
; --------------------------------------
ascii2num::
		ld	a,(hl)			; pierwszy obrot Y	
		and	0Fh			; minus ascii bits
		add	a			; x 2	
		ld	c,a
		add	a
		add	a
		add	a,c			; x 10
		ld	c,a			; save dziesiatki
		inc	hl
		ld	a,(hl)
		and	0Fh
		add	a,c			; dziesietne + jednoscioci
		inc	hl
		ret


